name = "PPCASpectra"
uuid = "4bc70558-c007-47c0-a71b-57423cb29c3c"
authors = ["Nikos Gianniotis"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
